### ISSUE TITLE
Server Crashes when setting a carriage on fire

### ISSUE THREAD

**Issue by VWASD** [TheGrimsey/Transportables#15]
**Describe the bug**
I was playing in an Aternos server with a modpack that uses the 1.18.1 version of this mod. I crafted the carriage and after seeing it I wanted to break it but when i saw i couldn't break it by punching it I tried to light it on fire using a flint and steel. After using the flint and steel both the server and my game crashed. Then I restarted the game and the server and when I tried to log in, the server crashed again.

**Mod version:** 1.1

**Fabric API version:**

**Minecraft version:** 1.18.1

**Comment by TheGrimsey** [comment]
Do you have a crash log?

**Comment by VWASD** [comment]
I will try to find it.
The game or server crash log?
This is the server crash report:

[13:09:44] [Server thread/ERROR]: Encountered an unexpected exception
--
2622 | net.minecraft.class_148: Ticking entity
2623 | at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:883) ~[server-intermediary.jar:?]
2624 | at net.minecraft.class_3176.method_3813(class_3176.java:324) ~[server-intermediary.jar:?]
2625 | at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[server-intermediary.jar:?]
2626 | at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) ~[server-intermediary.jar:?]
2627 | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
2628 | at java.lang.Thread.run(Unknown Source) [?:?]
2629 | Caused by: java.util.NoSuchElementException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
2630 | at java.util.AbstractList$Itr.next(Unknown Source) ~[?:?]
2631 | at net.minecraft.class_1890.handler$did000$damageReduction(class_1890.java:5574) ~[server-intermediary.jar:?]
2632 | at net.minecraft.class_1890.method_8219(class_1890.java:150) ~[server-intermediary.jar:?]
2633 | at net.minecraft.class_1309.method_6036(class_1309.java:1608) ~[server-intermediary.jar:?]
2634 | at net.minecraft.class_1309.method_6074(class_1309.java:1621) ~[server-intermediary.jar:?]
2635 | at net.minecraft.class_1309.method_5643(class_1309.java:1099) ~[server-intermediary.jar:?]
2636 | at net.minecraft.class_1297.method_5670(class_1297.java:496) ~[server-intermediary.jar:?]
2637 | at net.minecraft.class_1309.method_5670(class_1309.java:342) ~[server-intermediary.jar:?]
2638 | at net.minecraft.class_1297.method_5773(class_1297.java:452) ~[server-intermediary.jar:?]
2639 | at net.minecraft.class_1309.method_5773(class_1309.java:2311) ~[server-intermediary.jar:?]
2640 | at net.thegrimsey.transportables.entity.AbstractCarriageEntity.method_5773(AbstractCarriageEntity.java:77) ~[transportables-1.1.jar:?]
2641 | at net.minecraft.class_3218.method_18762(class_3218.java:699) ~[server-intermediary.jar:?]
2642 | at net.minecraft.class_1937.method_18472(class_1937.java:487) ~[server-intermediary.jar:?]
2643 | at net.minecraft.class_3218.method_31420(class_3218.java:360) ~[server-intermediary.jar:?]
2644 | at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
2645 | at net.minecraft.class_3218.method_18765(class_3218.java:328) ~[server-intermediary.jar:?]
2646 | at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
2647 | ... 5 more
2648 | Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
2649 | at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
2650 | at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
2651 | at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
2652 | at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
2653 | at java.util.ArrayList.get(Unknown Source) ~[?:?]
2654 | at net.minecraft.class_2371.get(class_2371.java:47) ~[server-intermediary.jar:?]
2655 | at java.util.AbstractList$Itr.next(Unknown Source) ~[?:?]
2656 | at net.minecraft.class_1890.handler$did000$damageReduction(class_1890.java:5574) ~[server-intermediary.jar:?]
2657 | at net.minecraft.class_1890.method_8219(class_1890.java:150) ~[server-intermediary.jar:?]
2658 | at net.minecraft.class_1309.method_6036(class_1309.java:1608) ~[server-intermediary.jar:?]
2659 | at net.minecraft.class_1309.method_6074(class_1309.java:1621) ~[server-intermediary.jar:?]
2660 | at net.minecraft.class_1309.method_5643(class_1309.java:1099) ~[server-intermediary.jar:?]
2661 | at net.minecraft.class_1297.method_5670(class_1297.java:496) ~[server-intermediary.jar:?]
2662 | at net.minecraft.class_1309.method_5670(class_1309.java:342) ~[server-intermediary.jar:?]
2663 | at net.minecraft.class_1297.method_5773(class_1297.java:452) ~[server-intermediary.jar:?]
2664 | at net.minecraft.class_1309.method_5773(class_1309.java:2311) ~[server-intermediary.jar:?]
2665 | at net.thegrimsey.transportables.entity.AbstractCarriageEntity.method_5773(AbstractCarriageEntity.java:77) ~[transportables-1.1.jar:?]
2666 | at net.minecraft.class_3218.method_18762(class_3218.java:699) ~[server-intermediary.jar:?]
2667 | at net.minecraft.class_1937.method_18472(class_1937.java:487) ~[server-intermediary.jar:?]
2668 | at net.minecraft.class_3218.method_31420(class_3218.java:360) ~[server-intermediary.jar:?]
2669 | at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
2670 | at net.minecraft.class_3218.method_18765(class_3218.java:328) ~[server-intermediary.jar:?]
2671 | at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
2672 | ... 5 more

**Comment by VWASD** [comment]
I also tried to do the same in a singleplayer world right now, i will paste here the crash log:
---- Minecraft Crash Report ----
// Don't do that.

Time: 5/29/23, 1:25 PM
Description: Colliding entity with block

java.util.NoSuchElementException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.AbstractList$Itr.next(AbstractList.java:377)
	at net.minecraft.class_1890.handler$enm000$damageReduction(class_1890.java:5574)
	at net.minecraft.class_1890.method_8219(class_1890.java:150)
	at net.minecraft.class_1309.method_6036(class_1309.java:1608)
	at net.minecraft.class_1309.method_6074(class_1309.java:1621)
	at net.minecraft.class_1309.method_5643(class_1309.java:1099)
	at net.minecraft.class_4770.method_9548(class_4770.java:125)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:925)
	at net.minecraft.class_1297.method_5852(class_1297.java:1019)
	at net.minecraft.class_1297.method_36974(class_1297.java:759)
	at net.minecraft.class_1297.method_5784(class_1297.java:728)
	at net.minecraft.class_1309.method_26318(class_1309.java:2247)
	at net.minecraft.class_1309.method_6091(class_1309.java:2192)
	at net.minecraft.class_1309.method_6007(class_1309.java:2643)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.thegrimsey.transportables.entity.AbstractCarriageEntity.method_5773(AbstractCarriageEntity.java:77)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.class_2371.get(class_2371.java:47)
	at java.base/java.util.AbstractList$Itr.next(AbstractList.java:371)
	... 26 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.util.AbstractList$Itr.next(AbstractList.java:377)
	at net.minecraft.class_1890.handler$enm000$damageReduction(class_1890.java:5574)
	at net.minecraft.class_1890.method_8219(class_1890.java:150)
	at net.minecraft.class_1309.method_6036(class_1309.java:1608)
	at net.minecraft.class_1309.method_6074(class_1309.java:1621)
	at net.minecraft.class_1309.method_5643(class_1309.java:1099)
	at net.minecraft.class_4770.method_9548(class_4770.java:125)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:925)
	at net.minecraft.class_1297.method_5852(class_1297.java:1019)
	at net.minecraft.class_1297.method_36974(class_1297.java:759)
	at net.minecraft.class_1297.method_5784(class_1297.java:728)
	at net.minecraft.class_1309.method_26318(class_1309.java:2247)
	at net.minecraft.class_1309.method_6091(class_1309.java:2192)
	at net.minecraft.class_1309.method_6007(class_1309.java:2643)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.thegrimsey.transportables.entity.AbstractCarriageEntity.method_5773(AbstractCarriageEntity.java:77)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)

-- Block being collided with --
Details:
	Block: Block{minecraft:fire}[age=0,east=false,north=false,south=false,up=false,west=false]
	Block location: World: (-4393,71,652), Section: (at 7,7,12 in -275,4,40; chunk contains blocks -4400,-64,640 to -4385,319,655), Region: (-9,1; contains chunks -288,32 to -257,63, blocks -4608,-64,512 to -4097,319,1023)
Stacktrace:
	at net.minecraft.class_1297.method_5852(class_1297.java:1019)
	at net.minecraft.class_1297.method_36974(class_1297.java:759)
	at net.minecraft.class_1297.method_5784(class_1297.java:728)
	at net.minecraft.class_1309.method_26318(class_1309.java:2247)
	at net.minecraft.class_1309.method_6091(class_1309.java:2192)
	at net.minecraft.class_1309.method_6007(class_1309.java:2643)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.thegrimsey.transportables.entity.AbstractCarriageEntity.method_5773(AbstractCarriageEntity.java:77)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Entity being checked for collision --
Details:
	Entity Type: transportables:carriage (net.thegrimsey.transportables.entity.CarriageEntity)
	Entity ID: 2427
	Entity Name: Carriage
	Entity's Exact location: -4391.36, 71.00, 651.68
	Entity's Block location: World: (-4392,71,651), Section: (at 8,7,11 in -275,4,40; chunk contains blocks -4400,-64,640 to -4385,319,655), Region: (-9,1; contains chunks -288,32 to -257,63, blocks -4608,-64,512 to -4097,319,1023)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1297.method_36974(class_1297.java:759)
	at net.minecraft.class_1297.method_5784(class_1297.java:728)
	at net.minecraft.class_1309.method_26318(class_1309.java:2247)
	at net.minecraft.class_1309.method_6091(class_1309.java:2192)
	at net.minecraft.class_1309.method_6007(class_1309.java:2643)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.thegrimsey.transportables.entity.AbstractCarriageEntity.method_5773(AbstractCarriageEntity.java:77)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Entity being ticked --
Details:
	Entity Type: transportables:carriage (net.thegrimsey.transportables.entity.CarriageEntity)
	Entity ID: 2427
	Entity Name: Carriage
	Entity's Exact location: -4391.36, 71.00, 651.68
	Entity's Block location: World: (-4392,71,651), Section: (at 8,7,11 in -275,4,40; chunk contains blocks -4400,-64,640 to -4385,319,655), Region: (-9,1; contains chunks -288,32 to -257,63, blocks -4608,-64,512 to -4097,319,1023)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Antidolorifico'/95, l='ServerLevel[New World]', x=-4394.50, y=71.00, z=652.02]]
	Chunk stats: 5018
	Level dimension: minecraft:overworld
	Level spawn location: World: (18,63,3), Section: (at 2,15,3 in 1,3,0; chunk contains blocks 16,-64,0 to 31,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 30087 game time, 18031 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 72700 (now: false), thunder time: 53942 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by VWASD** [comment]
I have been testing on a singleplayer server and (if it helps to find why the bug is happening) it seems like the game crashes whenever the carriage takes damage (fire, tnt, dropping it into the void...)

**Comment by TheGrimsey** [comment]
I can't replicate this with just Transportables. 

Another mod is assumptions that don't hold up. I do not consider this to be an issue with Transportables.

https://github.com/TheGrimsey/Transportables/assets/9167223/d8381ba9-8e9b-48d8-88d4-5d93ffe55c08
