### ISSUE TITLE
Mixin-related crash on 1.17

### ISSUE THREAD

**Issue by OakBricks-old** [TheGrimsey/Transportables#4]
**Describe the bug**
Crash happens on a modpack I have, it looks like the crash has to do with mixins, It appears to be a mod conflict

**Expected behavior**
I expected the game to launch without error

**Mod version:** 1.0.5

**Fabric API version:** 0.37.0

**Minecraft version:** 1.17.1

**Additional Context:**
Modlist will be given at request (but the list is also in the logs)

**Comment by TheGrimsey** [comment]
Do you have the crash log?

**Comment by OakBricks** [comment]
> 
> 
> Do you have the crash log?

looks like i accidently left the crashlog out lol, here is the only part of it i can find [log](https://pastebin.com/L9eaMgH9)

**Comment by OakBricks** [comment]
> 
> 
> Do you have the crash log?

yes, sorry for the shitty formatting, it's an early init crash, so no good logging

```Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_1299.<clinit>(class_1299.java:211)
	at net.minecraft.class_3103.<clinit>(class_3103.java:28)
	at net.minecraft.class_3031.<clinit>(class_3031.java:80)
	at net.minecraft.class_5464.<clinit>(class_5464.java:184)
	at net.minecraft.class_5458.method_30571(class_5458.java:46)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:266)
	at net.minecraft.class_2966.method_12851(class_2966.java:44)
	at net.minecraft.client.main.Main.main(Main.java:139)
	... 7 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinError: Encountered undecorated Accessor method in transportables.mixins.json:MinecartEntityAccessor applying to net.minecraft.class_1688
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.isAlreadyMerged(MixinApplicatorStandard.java:632)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.mergeMethod(MixinApplicatorStandard.java:548)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1054)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 29 more```

**Comment by TheGrimsey** [comment]
Seems to be related to a mixin bug SpongePowered/mixin#430

This was fixed a while ago but on only made it into the latest 0.8.3 release. At the time of writing this update hasn't made it into fabric yet.

**Comment by TheGrimsey** [comment]
I believe newer Fabric Loader versions should have this fixed now as they updated their mixin version.
