### ISSUE TITLE
World unusable after fall damage and entity ticking

### ISSUE THREAD

**Issue by benjiton** [TheGrimsey/Transportables#6]
I placed a Storage Carriage (transportables:chest_carriage) on my multiplayer world. I pushed it off a roof so that it suffers fall damage.
Then the server crashes. The same problem can be reproduced in singleplayer. The world is unusable.

`[15:24:49] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:883) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:823) ~[client-intermediary.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:99) ~[?:?]
	at net.minecraft.server.MinecraftServer.handler$bml000$modifiedRunLoop(MinecraftServer:4356) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:663) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.NoSuchElementException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.util.AbstractList$Itr.next(AbstractList.java:377) ~[?:?]
	at net.minecraft.enchantment.EnchantmentHelper.handler$hfg000$damageReduction(EnchantmentHelper:5574) ~[?:?]
	at net.minecraft.enchantment.EnchantmentHelper.getProtectionAmount(EnchantmentHelper:150) ~[?:?]
	at net.minecraft.entity.LivingEntity.applyEnchantmentsToDamage(LivingEntity:1608) ~[?:?]
	at net.minecraft.entity.LivingEntity.applyDamage(LivingEntity:1621) ~[?:?]
	at net.minecraft.entity.LivingEntity.damage(LivingEntity:1099) ~[?:?]
	at net.minecraft.entity.LivingEntity.handleFallDamage(LivingEntity:1522) ~[?:?]
	at net.minecraft.block.Block.onLandedUpon(Block:464) ~[?:?]
	at net.minecraft.entity.Entity.fall(Entity:1137) ~[?:?]
	at net.minecraft.entity.LivingEntity.fall(LivingEntity:318) ~[?:?]
	at net.minecraft.entity.Entity.move(Entity:656) ~[?:?]
	at net.minecraft.entity.LivingEntity.applyMovementInput(LivingEntity:2247) ~[?:?]
	at net.minecraft.entity.LivingEntity.travel(LivingEntity:2192) ~[?:?]
	at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2643) ~[?:?]
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2349) ~[?:?]
	at net.thegrimsey.transportables.entity.AbstractCarriageEntity.tick(AbstractCarriageEntity.java:77) ~[transportables-1.1.jar:?]
	at net.minecraft.server.world.ServerWorld.redirect$iha000$shouldTickEntity(ServerWorld:25680) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:699) ~[?:?]
	at net.minecraft.world.World.tickEntity(World:13595) ~[?:?]
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:360) ~[?:?]
	at net.minecraft.world.EntityList.forEach(EntityList:54) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:328) ~[?:?]
	at net.minecraft.server.MinecraftServer.redirect$cdn000$fixUpdateSuppressionCrashTick(MinecraftServer:5250) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:879) ~[client-intermediary.jar:?]
	... 6 more
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.minecraft.util.collection.DefaultedList.get(DefaultedList:47) ~[?:?]
	at java.util.AbstractList$Itr.next(AbstractList.java:371) ~[?:?]
	at net.minecraft.enchantment.EnchantmentHelper.handler$hfg000$damageReduction(EnchantmentHelper:5574) ~[?:?]
	at net.minecraft.enchantment.EnchantmentHelper.getProtectionAmount(EnchantmentHelper:150) ~[?:?]
	at net.minecraft.entity.LivingEntity.applyEnchantmentsToDamage(LivingEntity:1608) ~[?:?]
	at net.minecraft.entity.LivingEntity.applyDamage(LivingEntity:1621) ~[?:?]
	at net.minecraft.entity.LivingEntity.damage(LivingEntity:1099) ~[?:?]
	at net.minecraft.entity.LivingEntity.handleFallDamage(LivingEntity:1522) ~[?:?]
	at net.minecraft.block.Block.onLandedUpon(Block:464) ~[?:?]
	at net.minecraft.entity.Entity.fall(Entity:1137) ~[?:?]
	at net.minecraft.entity.LivingEntity.fall(LivingEntity:318) ~[?:?]
	at net.minecraft.entity.Entity.move(Entity:656) ~[?:?]
	at net.minecraft.entity.LivingEntity.applyMovementInput(LivingEntity:2247) ~[?:?]
	at net.minecraft.entity.LivingEntity.travel(LivingEntity:2192) ~[?:?]
	at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2643) ~[?:?]
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2349) ~[?:?]
	at net.thegrimsey.transportables.entity.AbstractCarriageEntity.tick(AbstractCarriageEntity.java:77) ~[transportables-1.1.jar:?]
	at net.minecraft.server.world.ServerWorld.redirect$iha000$shouldTickEntity(ServerWorld:25680) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:699) ~[?:?]
	at net.minecraft.world.World.tickEntity(World:13595) ~[?:?]
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:360) ~[?:?]
	at net.minecraft.world.EntityList.forEach(EntityList:54) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:328) ~[?:?]
	at net.minecraft.server.MinecraftServer.redirect$cdn000$fixUpdateSuppressionCrashTick(MinecraftServer:5250) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:879) ~[client-intermediary.jar:?]
	... 6 more`

**Mod version:**
1.1

**Fabric API version:**
0.46.6

**Minecraft version:**
1.18.1

**Comment by TheGrimsey** [comment]
I can't replicate this.

Can you replicate this without any other mods installed?

**Comment by TheGrimsey** [comment]
It has been almost a month, I can not replicate this issue. Reopen if you have more information
